# Generated by Django 2.2.4 on 2020-08-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='is_granted',
            field=models.BooleanField(default=False),
        ),
    ]
