# Generated by Django 2.2.4 on 2020-08-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0003_wish_is_granted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Granted',
        ),
    ]
